Cap 80 login screen styling
kressnick25/pointfluent pull request #11
Opened 2020-09-03 11:04 UTC by jmkraut

Did considerable tidy up on the login screen and added in error alert dialogs.

![image](https://user-images.githubusercontent.com/49256848/92107202-bfab5280-ee28-11ea-83b7-ef9e148efbfc.png)
![image](https://user-images.githubusercontent.com/49256848/92107214-c639ca00-ee28-11ea-8255-1473753f2ea1.png)

2020-09-03 12:08 UTC, kressnick25 commented on lib/auth/login.dart
> +  Future<void> connect(String username, String password) async {
This does nothing

2020-09-03 12:14 UTC, kressnick25 requested changes
Just need to change connect back to original UdContext.connect() rather than wrapped with a Future as this does not do anything currently

2020-09-03 12:15 UTC, kressnick25 requested changes

2020-09-03 12:15 UTC, kressnick25 commented on lib/auth/login.dart
> +      await connect(user.username, user.password).then((value) => setState(() {
Change this back to old call

2020-09-06 13:02 UTC, yuk0ga requested changes

2020-09-06 13:02 UTC, yuk0ga commented on lib/auth/login.dart
>          child: Column(
Change this child to a SingleChildScrollView(), and make this Column() the child of it. 
https://www.youtube.com/watch?v=2E9iZgg5TOY
This makes the login screen scrollable, which solves the bottom overflow.
Like this:
![Screen Shot 2020-09-05 at 15 51 07](https://user-images.githubusercontent.com/24802707/92298777-a7a21300-ef8f-11ea-86d8-2cfc1bc4283b.png)

2020-09-16 05:59 UTC, merged